### ISSUE TITLE
Compatibility issues with other spring-data modules ( allegedly ) 

### ISSUE THREAD

**Issue by RodionXedin** [Microsoft/spring-data-cosmosdb#108]
Hi, 

we have a pretty big project and it seems like there is a conflict somewhere. 
Basically the flow we tested was : 
1) Create a blank spring-boot project, add spring-data-cosmosdb and check connectivity
This worked nice. 
2) Do exactly same in main project 
This is where problems began : 

All we get is this error : 
`
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'ICNPushRepository': Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.microsoft.azure.spring.data.documentdb.repository.support.DocumentDbRepositoryFactoryBean]: No default constructor found; nested exception is java.lang.NoSuchMethodException: com.microsoft.azure.spring.data.documentdb.repository.support.DocumentDbRepositoryFactoryBean.<init>()
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1110)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1054)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getSingletonFactoryBeanForTypeCheck(AbstractAutowireCapableBeanFactory.java:881)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getTypeForFactoryBean(AbstractAutowireCapableBeanFactory.java:808)
	at org.springframework.beans.factory.support.AbstractBeanFactory.isTypeMatch(AbstractBeanFactory.java:544)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doGetBeanNamesForType(DefaultListableBeanFactory.java:425)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanNamesForType(DefaultListableBeanFactory.java:390)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanNamesForType(DefaultListableBeanFactory.java:384)
	at 
`

See full log uploaded.
[trace.txt](https://github.com/Microsoft/spring-data-cosmosdb/files/1930017/trace.txt)

We also have mongo and mssql connections defined in same project, might that be the case ? 

Please see pom attached.
[pom-reduced.txt](https://github.com/Microsoft/spring-data-cosmosdb/files/1930018/pom-reduced.txt)

Thank you for your time and help!

**Comment by sophiaso** [comment]
Hi @RodionXedin, thanks for opening issue. Checked the pom file you have provided, you are using `spring boot 1.5.9`, please use a different version for `spring-data-cosmosdb`, which was named `spring-data-documentdb`:

```
        <dependency>
            <groupId>com.microsoft.azure</groupId>
            <artifactId>spring-data-documentdb</artifactId>
            <version>0.1.5</version>
        </dependency>
```

Refer to the [wiki page for dependency management](https://github.com/Microsoft/spring-data-cosmosdb/wiki/Spring-Data-dependency-version-management)


There is a sample Spring Boot Application [here](https://github.com/Microsoft/azure-spring-boot/tree/0.1.x/azure-spring-boot-samples/azure-documentdb-spring-boot-sample).

Please have a try and any problem, contact with us.

**Comment by sophiaso** [comment]
If you want to use the `spring-data-documentdb` dependency directly, some configuration is required, [quick start here](https://github.com/Microsoft/spring-data-cosmosdb#quick-start).

Or follow the sample to use [azure-documentdb-spring-boot-starter](https://github.com/Microsoft/azure-spring-boot/blob/0.1.x/azure-spring-boot-samples/azure-documentdb-spring-boot-sample/pom.xml#L23).

**Comment by RodionXedin** [comment]
Hi Sophiaso, 

Unfortunately, switching the dependency, didn't change the problem. 

I actually started with this dependency but having this issue tried the spring-data-comsosdb as it was newer..

**Comment by sophiaso** [comment]
Hi @RodionXedin, could you provide a minimum reproducible application for your issue?(Including pom and java code) As in your shared pom, too many dependencies exist, and for the pom itself, is not a workable pom, some versions are missing etc. Thanks.

**Comment by xscript** [comment]
Closing this issue because of inactivity. Feel free to reopen it if this is still an issue.
