### ISSUE TITLE
Getting java.lang.ClassNotFoundException: org.springframework.data.mapping.MappingException on server startup

### ISSUE THREAD

**Issue by dixitprashant444** [Microsoft/spring-data-cosmosdb#122]
spring-data-cosmosdb version 2.0.3
org.springframework.boot' version '1.5.10.RELEASE'
Java version 8
Stack trace:
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.microsoft.azure.spring.data.documentdb.core.convert.MappingDocumentDbConverter]: Factory method 'mappingDocumentDbConverter' threw exception; nested exception is java.lang.NoClassDefFoundError: org/springframework/data/mapping/MappingException
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588)
        ... 75 common frames omitted
Caused by: java.lang.NoClassDefFoundError: org/springframework/data/mapping/MappingException
        at com.microsoft.azure.spring.data.documentdb.config.AbstractDocumentDbConfiguration.mappingDocumentDbConverter(AbstractDocumentDbConfiguration.java:35)
        at com.myapp.isb.svc.configurationdeployment.config.AppConfiguration$$EnhancerBySpringCGLIB$$d093aea8.CGLIB$mappingDocumentDbConverter$5(<generated>)
        at com.myapp.isb.svc.configurationdeployment.config.AppConfiguration$$EnhancerBySpringCGLIB$$d093aea8$$FastClassBySpringCGLIB$$c2c8eadf.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
        at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:358)
        at com.myapp.isb.svc.configurationdeployment.config.AppConfiguration$$EnhancerBySpringCGLIB$$d093aea8.mappingDocumentDbConverter(<generated>)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
        ... 76 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.springframework.data.mapping.MappingException
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:94)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 87 common frames omitted

**Comment by Incarnation-p-lee** [comment]
@dixitprashant444 
Thanks for you time and issue. The version of cosmosdb is almost align with spring boot, so from your log here. Could you please help to have a try on springframework 2.0.x ?
`spring-data-cosmosdb version 2.0.3
org.springframework.boot' version '1.5.10.RELEASE'`

**Comment by dixitprashant444** [comment]
@Incarnation-p-lee We can not upgrade version of spring boot (org.springframework.boot) to 2.0.x as it would cause issues in our existing application. Isn't spring-data-cosmosdb library backward compatible?

**Comment by Incarnation-p-lee** [comment]
@dixitprashant444 
Thanks for your response. I think you can try [spring-data-cosmosdb for spring 0.1.5](https://github.com/Microsoft/spring-data-cosmosdb/releases/tag/v0.1.5).

**Comment by dixitprashant444** [comment]
@Incarnation-p-lee 
With spring-data-cosmosdb 0.1.5, java.lang.ClassNotFoundException: org.springframework.data.mapping.MappingException is resolved. Now, server is up & running.
However, I am unable to save a record into collection. I get a different exception which says that "Property is null". **I think this library does not has capability to map custom objects (non primitive attributes) into collection.** 
Stack trace:
2018-05-22 11:33:57.397  INFO [configurationdeployment,55fb575ad4c79e49,55fb575ad4c79e49,false] 19616 --- [nio-8090-exec-7] c.m.a.d.internal.ServiceJNIWrapper       : Microsoft.Azure.Documents.ServiceInterop.dll copied to working directory.
2018-05-22 11:33:57.397  INFO [configurationdeployment,55fb575ad4c79e49,55fb575ad4c79e49,false] 19616 --- [nio-8090-exec-7] c.m.a.d.internal.ServiceJNIWrapper       : Microsoft.Azure.Documents.ServiceInterop.dll copied to working directory.
2018-05-22 11:33:57.414  INFO [configurationdeployment,55fb575ad4c79e49,55fb575ad4c79e49,false] 19616 --- [nio-8090-exec-7] c.m.a.d.internal.ServiceJNIWrapper       : DocumentDB.Spatial.Sql.dll copied to working directory.
2018-05-22 11:33:57.414  INFO [configurationdeployment,55fb575ad4c79e49,55fb575ad4c79e49,false] 19616 --- [nio-8090-exec-7] c.m.a.d.internal.ServiceJNIWrapper       : DocumentDB.Spatial.Sql.dll copied to working directory.
2018-05-22 11:33:57.422  INFO [configurationdeployment,55fb575ad4c79e49,55fb575ad4c79e49,false] 19616 --- [nio-8090-exec-7] c.m.a.d.internal.ServiceJNIWrapper       : ServiceJNI has loaded.
2018-05-22 11:33:57.422  INFO [configurationdeployment,55fb575ad4c79e49,55fb575ad4c79e49,false] 19616 --- [nio-8090-exec-7] c.m.a.d.internal.ServiceJNIWrapper       : ServiceJNI has loaded.
2018-05-22 11:34:01.926 ERROR [configurationdeployment,55fb575ad4c79e49,55fb575ad4c79e49,false] 19616 --- [nio-8090-exec-7] c.s.i.s.c.c.e.VndErrorUtil               : Property is null.
2018-05-22 11:34:01.926 ERROR [configurationdeployment,55fb575ad4c79e49,55fb575ad4c79e49,false] 19616 --- [nio-8090-exec-7] c.s.i.s.c.c.e.VndErrorUtil               : Property is null.
2018-05-22 11:34:01.938 ERROR [configurationdeployment,55fb575ad4c79e49,55fb575ad4c79e49,false] 19616 --- [nio-8090-exec-7] c.s.i.s.c.c.e.VndErrorUtil               : java.lang.IllegalArgumentException: Property is null.
2018-05-22 11:34:01.938 ERROR [configurationdeployment,55fb575ad4c79e49,55fb575ad4c79e49,false] 19616 --- [nio-8090-exec-7] c.s.i.s.c.c.e.VndErrorUtil               : java.lang.IllegalArgumentException: Property is null.
2018-05-22 11:34:01.939 ERROR [configurationdeployment,55fb575ad4c79e49,55fb575ad4c79e49,false] 19616 --- [nio-8090-exec-7] c.s.i.s.c.c.e.VndErrorUtil               :  at org.springframework.util.Assert.notNull(Assert.java:134)
2018-05-22 11:34:01.939 ERROR [configurationdeployment,55fb575ad4c79e49,55fb575ad4c79e49,false] 19616 --- [nio-8090-exec-7] c.s.i.s.c.c.e.VndErrorUtil               :  at org.springframework.util.Assert.notNull(Assert.java:134)
2018-05-22 11:34:01.942 ERROR [configurationdeployment,55fb575ad4c79e49,55fb575ad4c79e49,false] 19616 --- [nio-8090-exec-7] c.s.i.s.c.c.e.VndErrorUtil               :  at com.microsoft.azure.spring.data.documentdb.core.convert.MappingDocumentDbConverter.writeInternal(MappingDocumentDbConverter.java:112)
2018-05-22 11:34:01.942 ERROR [configurationdeployment,55fb575ad4c79e49,55fb575ad4c79e49,false] 19616 --- [nio-8090-exec-7] c.s.i.s.c.c.e.VndErrorUtil               :  at com.microsoft.azure.spring.data.documentdb.core.convert.MappingDocumentDbConverter.writeInternal(MappingDocumentDbConverter.java:112)
2018-05-22 11:34:01.944 ERROR [configurationdeployment,55fb575ad4c79e49,55fb575ad4c79e49,false] 19616 --- [nio-8090-exec-7] c.s.i.s.c.c.e.VndErrorUtil               :  at com.microsoft.azure.spring.data.documentdb.core.convert.MappingDocumentDbConverter.write(MappingDocumentDbConverter.java:85)
2018-05-22 11:34:01.944 ERROR [configurationdeployment,55fb575ad4c79e49,55fb575ad4c79e49,false] 19616 --- [nio-8090-exec-7] c.s.i.s.c.c.e.VndErrorUtil               :  at com.microsoft.azure.spring.data.documentdb.core.convert.MappingDocumentDbConverter.write(MappingDocumentDbConverter.java:85)
2018-05-22 11:34:01.951 ERROR [configurationdeployment,55fb575ad4c79e49,55fb575ad4c79e49,false] 19616 --- [nio-8090-exec-7] c.s.i.s.c.c.e.VndErrorUtil               :  at com.microsoft.azure.spring.data.documentdb.core.DocumentDbTemplate.upsert(DocumentDbTemplate.java:134)
2018-05-22 11:34:01.951 ERROR [configurationdeployment,55fb575ad4c79e49,55fb575ad4c79e49,false] 19616 --- [nio-8090-exec-7] c.s.i.s.c.c.e.VndErrorUtil               :  at com.microsoft.azure.spring.data.documentdb.core.DocumentDbTemplate.upsert(DocumentDbTemplate.java:134)
2018-05-22 11:34:01.955 ERROR [configurationdeployment,55fb575ad4c79e49,55fb575ad4c79e49,false] 19616 --- [nio-8090-exec-7] c.s.i.s.c.c.e.VndErrorUtil               :  at com.microsoft.azure.spring.data.documentdb.repository.support.SimpleDocumentDbRepository.save(SimpleDocumentDbRepository.java:61)
2018-05-22 11:34:01.955 ERROR [configurationdeployment,55fb575ad4c79e49,55fb575ad4c79e49,false] 19616 --- [nio-8090-exec-7] c.s.i.s.c.c.e.VndErrorUtil               :  at com.microsoft.azure.spring.data.documentdb.repository.support.SimpleDocumentDbRepository.save(SimpleDocumentDbRepository.java:61)

**Comment by Incarnation-p-lee** [comment]
@dixitprashant444 
Thanks for your log and quick response. It is just simple springbootapplication ? or Could you please help to provide some code to reproduce that exception ?

**Comment by Incarnation-p-lee** [comment]
@dixitprashant444 
Thanks for your information. This may related to unsupported id of int type. For now only support `String`. Could you please help to double check if it works on String id. And we will plan to add the fature for other primitive type.
```java
public class Job
{
    @Id
    private int id; // private String id;
    private List(State) jobStateList;
}
```

**Comment by dixitprashant444** [comment]
@Incarnation-p-lee 
It is just simple spring boot application. The example code that I had given you earlier is different from actual code. In actual code, we are using  private String id.
I tried with https://github.com/Azure/azure-documentdb-java/ and it works fine and we are going with this. We have decided to not use spring-data-cosmosdb as this is not production worthy library. I request you to please remove it from your blog/github until this is fully functional and ready for production use as this has wasted our efforts and time. 
Thank you for all your efforts.

**Comment by Matthew-Dong** [comment]
Thanks for the feedbacks. I'm wondering if you have tried with “private String id”? 

Also, please provides us with the sample project if possible, @Incarnation-p-lee can help reproduce and fix the issue.

**Comment by Incarnation-p-lee** [comment]
@dixitprashant444
### So you mean you provided log is not consistent with you code, right ? 
I notice that you mentioned the DataBase cannot take care custom object in you log. I attempt to recover you code from you log and enhance the customized part in below.

It works very well and we can see this domain in databse. From the information you provided, I am not sure if you have any problem from our README or sample code. If so, we can help to figure out which part may be missleading. 

Actually we have many users, and there is no issue from database primitive operations for now. As your provide information is not verfy clear, could you please help to provide minmal reproduced code ? So that we can figure out that where your wasted efforts and time to ?

```java
@Data
@Document(collection = "testCollection")
@AllArgsConstructor
@NoArgsConstructor
public class Domain {

    @Id
    private String id;

    private List<FirstState> states;
}

@Data
@AllArgsConstructor
@NoArgsConstructor
public class FirstState {

    private int id;

    private String name;

    private List<SecondState> states;
}

@Data
@AllArgsConstructor
@NoArgsConstructor
public class SecondState {

    private String location;

    private int cost;
}

@Repository
public interface DomainRepository extends DocumentDbRepository<Domain, String> {
}
```
And with login save code in below:
```java
	private final SecondState secondState1 = new SecondState("location-1", 1);
	private final SecondState secondState2 = new SecondState("location-2", 2);
	private final List<SecondState> secondStates = Arrays.asList(secondState1, secondState2);

	private final FirstState firstState1 = new FirstState(3, "fake-name-1", secondStates);
	private final FirstState firstState2 = new FirstState(4, "fake-name-2", secondStates);
	private final List<FirstState> firstStates = Arrays.asList(firstState1, firstState2);

	private final Domain domain = new Domain("id-1234", firstStates);

	this.repository.deleteAll();
	this.repository.save(domain);
	final Domain foundDomain = this.repository.findOne(domain.getId());
	Assert.notNull(foundDomain, "should found domain");
```

##### [Below domain in Cosmosdb](https://github.com/Incarnation-p-lee/Prepares/blob/master/images/cosmosdb.PNG)

My pom for your FYI
```
	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<java.version>1.8</java.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>com.microsoft.azure</groupId>
			<artifactId>spring-data-documentdb</artifactId>
			<version>0.1.5</version>
		</dependency>

		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<scope>provided</scope>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-autoconfigure</artifactId>
			<version>1.5.13.RELEASE</version>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>
```

**Comment by dixitprashant444** [comment]
Hope you have received the model classes, sent over email, to reproduce the issue.

**Comment by xscript** [comment]
Fix has been release. Closing this issue.
