### ISSUE TITLE
NullPointerException in TelemetryProxy

### ISSUE THREAD

**Issue by bognari** [Microsoft/spring-data-cosmosdb#200]
Hi,
I use cosmosdb (2.0.4) in my spring boot application inside a docker container. 
When I start my application outside the container everything works fine but when I start it inside the container I get a NPE at startup with this stacktrace:

```
Caused by: java.lang.NullPointerException: null
	at com.microsoft.azure.spring.data.cosmosdb.common.TelemetryProxy.lambda$mergeProperties$0(TelemetryProxy.java:63) ~[spring-data-cosmosdb-2.0.4.jar!/:na]
	at java.util.HashMap.forEach(HashMap.java:1289) ~[na:1.8.0_181]
	at com.microsoft.azure.spring.data.cosmosdb.common.TelemetryProxy.mergeProperties(TelemetryProxy.java:62) ~[spring-data-cosmosdb-2.0.4.jar!/:na]
	at com.microsoft.azure.spring.data.cosmosdb.common.TelemetryProxy.trackEvent(TelemetryProxy.java:39) ~[spring-data-cosmosdb-2.0.4.jar!/:na]
	at com.microsoft.azure.spring.data.cosmosdb.common.TelemetryProxy.trackEvent(TelemetryProxy.java:32) ~[spring-data-cosmosdb-2.0.4.jar!/:na]
	at com.microsoft.azure.spring.data.cosmosdb.common.TelemetryProxy.trackCustomEvent(TelemetryProxy.java:85) ~[spring-data-cosmosdb-2.0.4.jar!/:na]
	at com.microsoft.azure.spring.data.cosmosdb.DocumentDbFactory.<init>(DocumentDbFactory.java:56) ~[spring-data-cosmosdb-2.0.4.jar!/:na]
	at com.microsoft.azure.spring.data.cosmosdb.config.AbstractDocumentDbConfiguration.documentDbFactory(AbstractDocumentDbConfiguration.java:42) ~[spring-data-cosmosdb-2.0.4.jar!/:na]
```

as far as I can see the problem is, that 
the values inside the mergedProperties can be null because you put the result from getHashMac() ([0]) inside the Map ([1]) and the result of the method is inside my docker container null, because ifconfig is not installed. 

[0]:
https://github.com/Microsoft/spring-data-cosmosdb/blob/2fd030864f1b8ff6cfeebb18cebe7c8f6c0f3852/src/main/java/com/microsoft/azure/spring/data/cosmosdb/common/GetHashMac.java#L40-L58

[1]:
https://github.com/Microsoft/spring-data-cosmosdb/blob/2fd030864f1b8ff6cfeebb18cebe7c8f6c0f3852/src/main/java/com/microsoft/azure/spring/data/cosmosdb/common/TelemetryProxy.java#L71-L78

This is my Dockerfile:

```
FROM [openjdk:8-jdk]
VOLUME /tmp
ARG JAR_FILE
COPY ${JAR_FILE} app.jar
COPY ... 
EXPOSE 8080 80
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
```
my currently workaround is to add ``RUN apt-get update && apt-get install net-tools`` to the Dockerfile

p.s. in general I think the filter in 
https://github.com/Microsoft/spring-data-cosmosdb/blob/2fd030864f1b8ff6cfeebb18cebe7c8f6c0f3852/src/main/java/com/microsoft/azure/spring/data/cosmosdb/common/TelemetryProxy.java#L62-L66

is a very bad idea because it will produce a ConcurrentModificationException if it filters, because you remove an entry from map without the use of the iterator in (forEach)

p.p.s I know my English is horrible...

**Comment by Incarnation-p-lee** [comment]
@bognari Thanks for you issue and finding. 
Yes, it is one legacy code with defect here. We will fix it later and make code more elegant.

**Comment by yaweiw** [comment]
@bognari is correct. Guess we can use removeIf instead.

**Comment by Incarnation-p-lee** [comment]
In fact, we do **NOT** need these part of login in proxy. I will refine this and make it simple.
