### ISSUE TITLE
Support for Spring Boot 2.1.X

### ISSUE THREAD

**Issue by zdragkas** [Microsoft/spring-data-cosmosdb#302]
spring-data-cosmosdb conflicts with Spring Boot 2.1.X dependencies.

Are there any plans to support it?

**Comment by zdragkas** [comment]
Just upgrade spring-data-cosmosdb-samples parent pom to spring boot version 2.1.0.RELEASE and then you get:
***************************
APPLICATION FAILED TO START
***************************

Description:

The bean 'httpRequestHandlerAdapter', defined in class path resource [org/springframework/data/rest/webmvc/config/RepositoryRestMvcConfiguration.class], could not be registered. A bean with that name has already been defined in class path resource [org/springframework/boot/autoconfigure/web/servlet/WebMvcAutoConfiguration$EnableWebMvcConfiguration.class] and overriding is disabled.

Action:

Consider renaming one of the beans or enabling overriding by setting spring.main.allow-bean-definition-overriding=true

**Comment by Incarnation-p-lee** [comment]
@zdragkas 
Thanks for you information. It is quit important to us and I will take a look into it.

**Comment by Incarnation-p-lee** [comment]
@zdragkas 
That may be the conflict between spring-data-commons 2.0.x version with spring-boot 2.1.x version. Our package will support spring-data-commons 2.1.x for spring-boot 2.1.x in short future.

**Comment by Incarnation-p-lee** [comment]
@zdragkas 
The above PR eliminate the explicit dependency from pom and leverage spring boot parent. The spring boot version greater than `2.0.4RELEASE` may throw that exception.

For spring-boot version 2.1.x, you may need to specific explicit spring-data-commons version like `2.0.7.RELEASE` for workaround, or you may got the exception like below.
```
Caused by: java.lang.IllegalStateException: You have defined query method in the repository but you don't have any query lookup strategy defined. The infrastructure apparently does not support query methods!
        at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.<init>(RepositoryFactorySupport.java:545) ~[spring-data-commons-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
        at org.springframework.data.repository.core.support.RepositoryFactorySupport.getRepository(RepositoryFactorySupport.java:324) ~[spring-data-commons-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
        at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.lambda$afterPropertiesSet$5(RepositoryFactoryBeanSupport.java:297) ~[spring-data-commons-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
        at org.springframework.data.util.Lazy.getNullable(Lazy.java:211) ~[spring-data-commons-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
        at org.springframework.data.util.Lazy.get(Lazy.java:94) ~[spring-data-commons-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
```

**Comment by Incarnation-p-lee** [comment]
@zdragkas
Close this issue as sdk for spring boot 2.1.x has released already.
