### ISSUE TITLE
Spring Data Cosmos 3.0.0.M1 is not compatible with Spring Boot 2.1.X

### ISSUE THREAD

**Issue by dsibilio** [microsoft/spring-data-cosmosdb#406]
spring-data-cosmosdb 3.0.0.M1 is not compatible with Spring Boot 2.1.X (it seems spring-data-commons 2.1.X is the real culprit).

You can refer to #302 , as the error is the same:

```
Caused by: java.lang.IllegalStateException: You have defined query method in the repository but you don't have any query lookup strategy defined. The infrastructure apparently does not support query methods!
        at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.<init>(RepositoryFactorySupport.java:545) ~[spring-data-commons-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
        at org.springframework.data.repository.core.support.RepositoryFactorySupport.getRepository(RepositoryFactorySupport.java:324) ~[spring-data-commons-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
        at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.lambda$afterPropertiesSet$5(RepositoryFactoryBeanSupport.java:297) ~[spring-data-commons-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
        at org.springframework.data.util.Lazy.getNullable(Lazy.java:211) ~[spring-data-commons-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
        at org.springframework.data.util.Lazy.get(Lazy.java:94) ~[spring-data-commons-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
```
This issue has been closed for spring-data-cosmosdb 2.1.X but is still present in 3.0.0.M1.

PS. *I have noticed that reactive implementation has been added with #394 on master, does this mean that 3.0.0.X is currently dead and 2.1.3 is supposed to provide the reactive capabilities for spring data cosmosDb repositories?*

**Comment by christopheranderson** [comment]
Do not use 3.0.0.M1 - we're aligning our versions to match the rest of Spring Boot ecosystem.
