### ISSUE TITLE
Spring data stopping after copying data to CosmosDB

### ISSUE THREAD

**Issue by dmendez1** [microsoft/spring-data-cosmosdb#458]
Here is the output where it stop after running mvn clean spring-boot:run . Found this code from a Microsoft tutorial, could it be I'm not using a wrapper? I tried using mvnw but the command would not work. 
<img width="1257" alt="wtf" src="https://user-images.githubusercontent.com/31740608/70189495-14af1200-16b9-11ea-879a-d3fb31e64880.png">

2019-12-04 16:50:29.136 ERROR 15728 --- [ctor-http-nio-2] r.n.resources.PooledConnectionProvider   : [id: 0x32862e38, L:/10.120.14.38:54698 - R:webprogdata-westus.documents.azure.com/40.112.241.18:443] Pooled connection observed an error

java.net.SocketException: Connection reset
	at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:345) ~[na:na]
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:376) ~[na:na]
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:247) ~[netty-buffer-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1147) ~[netty-buffer-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350) ~[netty-transport-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148) ~[netty-transport-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700) ~[netty-transport-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635) ~[netty-transport-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552) ~[netty-transport-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514) ~[netty-transport-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050) ~[netty-common-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.43.Final.jar:4.1.43.Final]
	at java.base/java.lang.Thread.run(Thread.java:830) ~[na:na]

**Comment by kushagraThapar** [comment]
@dmendez1 Can you share the code sample you are using. 
Also, if you run the application in debug mode, you should get more detailed logs. Right now the logs are only showing reactor netty connection pool provider issue. Please share more logs so we can debug.

**Comment by kushagraThapar** [comment]
@dmendez1  - is the issue still happening ?
