### ISSUE TITLE
 SSL Exception with spring-data-cosmosdb SDK version “2.3.0” 

### ISSUE THREAD

**Issue by SaurabhWajpe** [microsoft/spring-data-cosmosdb#556]
We have one microservice in JAVA Spring boot deployed on AKS and we are using spring-data-cosmosdb SDK version “2.3.0” to save data in cosmosDB asynchronously. Below are the dependencies that we are using in pom.xml.

`
```
<dependency>
<groupId>com.microsoft.azure</groupId>
<artifactId>azure-cosmosdb-spring-boot-starter</artifactId>
<version>2.2.0</version>
</dependency>
<dependency>
<groupId>com.microsoft.azure</groupId>
<artifactId>spring-data-cosmosdb</artifactId>
<version>2.3.0</version>
</dependency>

```
`

We are logging into Application Insights with dependency tracking. We can see “SSLException” very often with OTHER CONNECT as dependency in our logs. Below is the stack trace for the issue:

`javax.net.ssl.SSLException: SSLEngine closed already
at io.netty.handler.ssl.SslHandler.wrap(SslHandler.java:854)
at io.netty.handler.ssl.SslHandler.wrapAndFlush(SslHandler.java:811)
at io.netty.handler.ssl.SslHandler.flush(SslHandler.java:792)
at io.netty.handler.ssl.SslHandler.flush(SslHandler.java:1939)
at io.netty.handler.ssl.SslHandler.closeOutbound0(SslHandler.java:668)
at io.netty.handler.ssl.SslHandler.closeOutbound(SslHandler.java:652)
at io.netty.handler.ssl.SslHandler.closeOutbound(SslHandler.java:640)
at com.azure.data.cosmos.internal.directconnectivity.rntbd.RntbdRequestManager.close(RntbdRequestManager.java:391)
at io.netty.channel.AbstractChannelHandlerContext.invokeClose(AbstractChannelHandlerContext.java:622)
at io.netty.channel.AbstractChannelHandlerContext.access$1200(AbstractChannelHandlerContext.java:61)
at io.netty.channel.AbstractChannelHandlerContext$11.run(AbstractChannelHandlerContext.java:611)
at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.base/java.lang.Thread.run(Unknown Source)`

We suspect that it’s trying to close the connection which is already closed. We don’t have any custom configurations and we are following Spring azure cosmos default configurations. 

![image](https://user-images.githubusercontent.com/30463282/104692710-6f28f780-572e-11eb-8d2b-dafdb8ae1260.png)

**Comment by chenrujun** [comment]
Hi, @SaurabhWajpe , I copied this issue to our new repo. So I'll close this issue.
